# Generated by Django 5.1.3 on 2024-12-01 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aalim_profile', '0003_remove_aalimprofile_poetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('line_sets', models.CharField(choices=[('2', 'Two-Line Set'), ('4', 'Four-Line Set')], default=2, max_length=1)),
                ('two_line_set', models.TextField(blank=True, null=True)),
                ('four_line_set', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poetry', to='aalim_profile.aalimprofile')),
            ],
        ),
    ]
