# Generated by Django 5.1.3 on 2024-12-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poetry',
            name='four_line_set',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='two_line_set',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
