# Generated by Django 5.1.3 on 2024-12-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0002_alter_poetry_four_line_set_alter_poetry_two_line_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poetry',
            name='two_line_set',
        ),
    ]
