# Generated by Django 5.1.3 on 2024-12-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aalim_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aalimprofile',
            name='books',
        ),
        migrations.AlterField(
            model_name='aalimprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/aalim_images/'),
        ),
    ]
