# Generated by Django 5.1.3 on 2024-12-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aalim_profile', '0002_remove_aalimprofile_books_alter_aalimprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aalimprofile',
            name='poetry',
        ),
    ]
