# Generated by Django 5.1.3 on 2024-12-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aalim_profile', '0003_remove_aalimprofile_poetry'),
    ]

    operations = [
        migrations.AddField(
            model_name='aalimprofile',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aalimprofile',
            name='notable_contributions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
