# Generated by Django 5.1.3 on 2024-12-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aalim_profile', '0004_aalimprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aalimprofile',
            name='dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aalimprofile',
            name='dod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
