# Generated by Django 5.1.3 on 2024-12-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('English', 'ENG'), ('Urdu', 'UR'), ('Arabic', 'AR'), ('Persian', 'PR')], max_length=50),
        ),
    ]
