# Generated by Django 5.1.3 on 2024-12-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_created_at_book_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
